### ISSUE TITLE
Developer notes on compatibility (Important)

### ISSUE THREAD

**Issue by abbasnaqdi** [abbasnaqdi/nekoray-macos#16]
I am aware that the script is not compatible with the new changes, but life is hard, and I don't have enough time to adapt right now.
I will do this as soon as possible (although I hope other developers will contribute to the development of this script and make compatibility).

So wait for now until I get the desired time.

**Comment by aaaamirabbas** [comment]
Don't be disappointed, **I will start modifying the builder script next week.**

**Comment by abbasnaqdi** [comment]
I can only publish version 3.3 and 3.5 for now (I think it will meet your need for now)
https://github.com/abbasnaqdi/nekoray-macos/releases
