### ISSUE TITLE
Looking forward to the new version

### ISSUE THREAD

**Issue by lxtx528** [abbasnaqdi/nekoray-macos#17]
Brother, when will it be updated? I am looking forward to your work.

**Comment by aaaamirabbas** [comment]
https://github.com/aaaamirabbas/nekoray-macos/issues/16

**Comment by abbasnaqdi** [comment]
I can only publish version 3.3 and 3.5 for now (I think it will meet your need for now)
https://github.com/abbasnaqdi/nekoray-macos/releases
