### ISSUE TITLE
REQUEST: an update to the latest version

### ISSUE THREAD

**Issue by elrazez** [abbasnaqdi/nekoray-macos#18]
hello,
hope you're doing well.
since there aren't any good macos clients out there, and with the need of a REALITY protocol client. an update to 3.7 [https://github.com/MatsuriDayo/nekoray/releases/tag/3.7] would be highly appreciated.
thank you

**Comment by abbasnaqdi** [comment]
**https://github.com/abbasnaqdi/nekoray-macos/releases**
