### ISSUE TITLE
Regarding the repair issues of the modified version 3.3 system

### ISSUE THREAD

**Issue by lxtx528** [abbasnaqdi/nekoray-macos#20]
Hello brother! The version you modified is for Catalina OS 10.15.7, new version 3.3. It can now be installed successfully, but the application cannot be opened. Can you optimize it again?

**Comment by abbasnaqdi** [comment]
For now, you will have to wait until I find enough time to make the corrections, or you can go ahead and help fix the problems yourself.

**Comment by abbasnaqdi** [comment]
**New release published, test it.
https://github.com/abbasnaqdi/nekoray-macos/releases/**

**Comment by lxtx528** [comment]
Updated, very useful, thank you brother!

Abbas Naqdi ***@***.***> 于2023年7月21日周五 11:18写道：
