### ISSUE TITLE
start error

### ISSUE THREAD

**Issue by daerdai** [abbasnaqdi/nekoray-macos#22]
Try to start the config, but the core has not listened to the grpc port, so restart it...
start core error occurred: execve: No such file or directory

**Comment by sotnikov-link** [comment]
VPN mode for any core shows me log

```
[Error] Core exited, restarting.
start core error occurred: execve: No such file or directory
start core error occurred: execve: No such file or directory
```

**Comment by abbasnaqdi** [comment]
**New release published, test it.
https://github.com/abbasnaqdi/nekoray-macos/releases/**

**Comment by lgs3137** [comment]
> **New release published, test it. https://github.com/abbasnaqdi/nekoray-macos/releases/**

![image](https://github.com/abbasnaqdi/nekoray-macos/assets/1278141/5c71e8f0-3252-47d2-8745-64195a9eefb4)

**Comment by abbasnaqdi** [comment]
Use proxy mode.
VPN mode will not work.
