### ISSUE TITLE
درود  

### ISSUE THREAD

**Issue by hosseinkhojany** [abbasnaqdi/nekoray-macos#32]
ممنون برای این ریپازیتوری فوق العاده من یک سوال داشتم امکان استفاده از این ریپازیتوری در فرمورک های کراس پلتفرم مثل فلاتر یا ری اکت نیتیو هست ؟

**Comment by abbasnaqdi** [comment]
سلام خواهش میکنم
سوالتون رو متوجه نشدم، دو تکنولوژی که نام بردین برای ساخت اپلیکیشن های موبایل هستن و nekoray هیچ ارتباطی با اینها نداره
برای سیستم عامل های موبایل باید از نرم‌افزار های دیگه ای استفاده کنید مثلا برای اندروید به ریپازیتوری زیر مراجعه کنید
https://github.com/MatsuriDayo/NekoBoxForAndroid

**Comment by hosseinkhojany** [comment]
عباس جان میتونی کمکی به من در خروجی گرفتن از برنامه مک او اسی در حالت developer id  بکنید با هزینه ؟

**Comment by abbasnaqdi** [comment]
سلام من تجربه ای در درخواستی که دارین ندارم، در واقع اصلا برنامه نویس macOS نیستم و تخصصم توسعه اپلیکیشن های اندرویده.
