### ISSUE TITLE
Intel version flashback

### ISSUE THREAD

**Issue by lxtx528** [abbasnaqdi/nekoray-macos#33]
Brother, thank you for your update. There is a small issue. The latest version of Intel version will flash back when updating the subscription. Is there a way to handle it?

**Comment by abbasnaqdi** [comment]
I don't understand what you mean by flashback
Can you explain more?

**Comment by lxtx528** [comment]
When updating a subscription, it will flash back, basically every update
will flash back. Is it because I have too many subscriptions?

Abbas Naqdi ***@***.***> 于 2023年8月22日周二 03:02写道：

**Comment by abbasnaqdi** [comment]
I don't know, I just build the software and have no involvement in its operation.
Ask the original developers.
