### ISSUE TITLE
Build stopped with error

### ISSUE THREAD

**Issue by armdn** [abbasnaqdi/nekoray-macos#37]
Well, after issuing "sudo bash builder.sh" (without sudo not work!!!) it starting log this and stopped on this:

`HEAD is now at 7cc7534 Merge pull request #29 from makoni/main
HEAD is now at 7cc7534 Merge pull request #29 from makoni/main
Fetching origin
HEAD is now at 7cc7534 Merge pull request #29 from makoni/main
HEAD is now at 7cc7534 Merge pull request #29 from makoni/main
Fetching origin
HEAD is now at 7cc7534 Merge pull request #29 from makoni/main
HEAD is now at 7cc7534 Merge pull request #29 from makoni/main
Fetching origin
HEAD is now at 7cc7534 Merge pull request #29 from makoni/main
HEAD is now at 7cc7534 Merge pull request #29 from makoni/main
Fetching origin
HEAD is now at 7cc7534 Merge pull request #29 from makoni/main
HEAD is now at 7cc7534 Merge pull request #29 from makoni/main
Fetching origin
HEAD is now at 7cc7534 Merge pull request #29 from makoni/main
HEAD is now at 7cc7534 Merge pull request #29 from makoni/main
bash: libs/get_source.sh: No such file or directory`

What is that get_source.sh and where i can get this?

**Comment by abbasnaqdi** [comment]
The script must be adapted to the new source
For now, you have to wait until I find time to fix it, or do it yourself.

**Comment by abbasnaqdi** [comment]
Fixed.
