### ISSUE TITLE
Nekoray (macOS) برنامه Routing آموزش نصب و تنظیمات

### ISSUE THREAD

**Issue by Phoenix-999** [abbasnaqdi/nekoray-macos#38]
سلام به همه رفقای عزیز
این مقاله را تنظیم کردیم, امیدوارم که مورد استفاده قرار بگیرد

شما میتوانید از ربات آموزشی تلگرام برای دریافت این آموزش ها نیز استفاده کنید
[@IRAN_VPN_Guide_bot](https://t.me/IRAN_VPN_Guide_bot)

دانلود نسخه PDF
**[NekoRay-macOS (Intel + Apple).pdf](https://github.com/iranxray/hope/files/12565982/NekoRay-macOS.Intel.%2B.Apple.pdf)**
__________________________________________________________________________________________

نرم افزار `NekoRay` که مجهز به هسته `1.8.3 Xray` میباشد و برای `macOS (Intel + Apple)` طراحی شده و حتا با macOS های قدمی مثل **10.15.7 Catalina** به خوبی سازگاری دارد.

شما میتوانید از [لینک فوق به صفحه گیتهاب این نرم افزار](https://github.com/abbasnaqdi/nekoray-macos/releases) دسترسی پیدا کنید و فایلهای اجرایی را از این صفحه دانلود کنید یا از لینک زیر برای دریافت آخرین نسخه استفاده کنید و با تشکر ویژه از @abbasnaqdi

**[لینک دانلود مستقیم اینجا کلیک کنید](https://github.com/abbasnaqdi/nekoray-macos/releases/latest/download/nekoray_amd64.zip
)** 

__________________________________________________________________________________________
## آموزش ابتدای نصب و تنظیمات

همانطور که در تصویر زیر مشاهده می‌کنید در ابتدا با فشار دادن کلید `Update` مطمئن شوید که برنامه شما با آخرین نسخه به روز رسانی شده است. بعد از انجام این قسمت با انتخاب گزینه `Program` پنجره کشویی را باز کنید که در آن گزینه‌های مختلفی را شاهد خواهید بود

![NekoRay-macOS-01](https://github.com/iranxray/hope/assets/127796122/debcc4da-3ca8-4a3b-a98a-8c4ebd92afe9)

مطمئن شوید که لینک کانفیگ خود را از قبل کپی کرده‌اید و در حافظه کامپیوتر ذخیره کرده‌اید، در مرحله بعد همانطور که در تصویر زیر مشاهده می‌کنید در پنجره کشویی باز شده گزینه `Add profile from clipboard`راه انتخاب کنید که کانفیگ شما به صورت خودکار به برنامه اضافه شود

![NekoRay-macOS-02](https://github.com/iranxray/hope/assets/127796122/568a39fb-5c2d-4f3d-80da-220bd13cea1c)

همانطور که می‌بینید کانفیگ شما به درستی به برنامه اضافه شده است حالا با دبل کلیک کردن بر روی اسم VPN خود وارد تنظیمات اختصاصی  شوید.
ما برای اتصال موفق نیاز داریم که تغییراتی را در این قسمت انجام دهیم

![NekoRay-macOS-03](https://github.com/iranxray/hope/assets/127796122/c1430171-9ed8-49f6-b432-976b0e0812ca)

در این مرحله نیاز داریم که تغییراتی را در قسمت `ALPN`و `Fingerprint` و همچنین اگر مایلید در قسمت `Flow` طبق تصویر زیر وارد کنید.

**ALPN**: `h3,h2,http/1.1,spdy/3.1`
**Fingerprint**: `Chrome`
**Flow**: `xtls-rprx-vision-udp443`

لازم به ذکر است برای کاربرانی که اطلاعات و تخصص بیشتری در این تنظیمات دارند می‌توانید به صورت دلخواه مقادیر دیگر این قسمت را برای کارایی بهتر VPN خود تغییر دهید.

بعد از اعمال تمام تغییرات کلید `OK` را فشار دهید تا ذخیره شود.

![NekoRay-macOS-04](https://github.com/iranxray/hope/assets/127796122/8420409c-e3fe-409f-95d3-9218385b1173)

حالا به صفحه قبلی برمی‌گردیم بر روی نام وی پی ان خود کلید سمت راست را اجرا می‌کنیم و بعد از باز شدن پنجره کشویی با کلیک کردن بر روی کلمه `Start` وی پی ان ما شروع به کار کردن و اتصال خواهد کرد.

نکته بسیار مهم قبل از شروع اتصال مطمئن شوید که گزینه `System Proxy` انتخاب و تیک خورده باشد

کاربرانی که معلومات و تخصص بیشتری در این تنظیمات دارند می‌توانید از گزینه `Tune Mode` نیز استفاده کنید.

![NekoRay-macOS-05](https://github.com/iranxray/hope/assets/127796122/a0b5dfb9-2333-410e-9c61-478773fe9e63)

__________________________________________________________________________________________

## آموزش تنظیمات Routing و DNS

این قسمت را از کاربرا‌ن‌تان بخواهید که انجام دهند. چرا که ایده‌ال ترین حالت این است که اساسا ترافیک داخلی ایران به سمت پروکسی سرور شما ارسال نشود. مثلا اپلیکیشن `NekoRay` برای ما این امکان را فراهم می‌کند که به سادگی مشخص کنیم ترافیک داخلی از پروکسی عبور نکند و فقط ترافیک خارجی به سمت پروکسی سرور ارسال شود

مزایای استفاده از Routing
کاهش احتمال شناسایی سرور
کاهش ترافیک سرور و در نتیجه بالا رفتن **کیفیت**
کاهش هزینه‌های سرور (اگر بابت ترافیک هزینه جداگانه پرداخت می‌کنید.)
``
ابتدا در این مرحله با کلیک کردن بر روی گزینه `Preferences` پنجره کشویی را باز می‌کنیم و بر روی گزینه `Routing Settings` کلیک می‌کنیم تا به قسمت تنظیمات اختصاصی این قسمت وارد شویم.

ترجیحاً برای اطمینان پیدا کردن از اعمال صحیح این تغییرات وی پی ان خود را خاموش کنید.

![NekoRay-macOS-06](https://github.com/iranxray/hope/assets/127796122/a8ea8a4c-54d4-44bb-9a8c-aa1b8dd588db)

همانطور که در تصویر مشاهده می‌کنید تغییرات را در قسمت Common انجام دهید و  با کلیک کردن بر کلید `OK` این تغییرات را در این قسمت ذخیره کنید.

![NekoRay-macOS-07](https://github.com/iranxray/hope/assets/127796122/18dbf665-0700-4df1-9bd3-115fb8f64e95)

در این قسمت ما می‌توانیم DNS خود را تنظیم کنیم به صورت خودکار نرم‌افزار DNS را بر روی گوگل تنظیم کرده است که ترجیحاً نیازی به تغییر آن نیست ولی برای کاربرانی که مشتاق به تغییر  مقادیر هستند می‌توانید از یکی از آدرس‌های زیر استفاده کنید یا هر IP آدرس  دیگری دیگری که مد نظر شما باشد.

**Remote DNS**:
            `https://1.1.1.1/dns-query`
            `https://dns.google/dns-query`
            `https://dns.quad9.net/dns-query`
            `https://doh.opendns.com/dns-query`
            `https://doh.cleanbrowsing.org/doh/family-filter/`
            `https://dns.adguard.com/dns-query`

![NekoRay-macOS-08](https://github.com/iranxray/hope/assets/127796122/50728ef2-69b3-458f-a5e0-f486f2200e20)

در مرحله نهایی که **قسمت مهم** این تغییرات می‌باشد مقادیر زیر را طبق تصویر وارد کنید

**Direct IP**: `geoip:ir`
**Direct Domain**: `regexp:^.+\.ir$` and `geosite:category-ir`
**Block Domain**: `geosite:category-ads-all`

این تنظیمات باعث شود که در هنگام اتصال به VPN تمام وب سایت‌ها که پیشوند `IR.` یا دیگر دامین‌هایی که متعلق به سرورهای ایرانی می‌باشند پروکسی VPN شما عبور نکنند و به صورت مستقیم در مرورگر شما باز شوند. قسمت‌های دیگر برای مسدود کردن تبلیغات طراحی و تنظیم شده.

کاربرانی که اطلاعات و تخصص بیشتری در این زمینه دارند می‌توانند با اضافه کردن  آی‌پی‌ها یا مقادیر دیگر مکانیزم روتیک خود را تقویت دهند.

![NekoRay-macOS-09](https://github.com/iranxray/hope/assets/127796122/f578984e-049e-4556-8166-a2759f1a10fb)

با کلیک کردن بر روی کلید `OK` کار ما در اینجا به پایان خواهد رسید و تمام این تغییرات در برنامه ذخیره خواهد شد و در هنگام اتصال به VPN اعمال خواهند شد.

حالا می‌توانید به صفحه اصلی برگردید و با اجرای کلید سمت راست گزینه **Start** را برای شروع مجدد وی پی ان خود کلیک کنید.

کاربرانی که از گزینه `Tune Mode` استفاده می‌کنید و با خطا مواجه می‌شوید کامند لاین زیر را در ترمینال اجرا کنید و مراحل را از اول انجام دهید باید مشکل اتصال شما حل شود.

`sudo /Applications/nekoray.app/Contents/MacOS/nekoray`

__________________________________________________________________________________________

**Comment by abbasnaqdi** [comment]
This tutorial should be placed in another section.
It is irrelevant in the issues of this project.
