### ISSUE TITLE
new version

### ISSUE THREAD

**Issue by Rasoul-Karimi** [abbasnaqdi/nekoray-macos#39]
hi. plase relase new version : 3.21

**Comment by abbasnaqdi** [comment]
The original source is not compatible with macOS.
In the next version, I will participate in its compatibility and correct the problems.

Be patient.

**Comment by abbasnaqdi** [comment]
https://github.com/abbasnaqdi/nekoray-macos/releases/tag/3.21

**Comment by narakai** [comment]
Both builds failed on Mac os  Sonama 14.0.

**Comment by abbasnaqdi** [comment]
https://github.com/abbasnaqdi/nekoray-macos/issues/40#issuecomment-1740546839
