### ISSUE TITLE
New version not available

### ISSUE THREAD

**Issue by lxtx528** [abbasnaqdi/nekoray-macos#44]
Hello, brother! The new version 3.24 cannot be opened on Intel versions Mac OS 11.7.10 and Mac OS 10.15.7, both of which flash back.

**Comment by XopoIII** [comment]
+1

**Comment by abbasnaqdi** [comment]
**Please run the application like this in the terminal and send me the crash log:**
./nekoray_amd64.app/Contents/MacOS/nekoray
Or
./nekoray_arm64.app/Contents/MacOS/nekoray

**Comment by abbasnaqdi** [comment]
Try this version.
https://github.com/abbasnaqdi/nekoray-macos/releases/tag/3.25
