### ISSUE TITLE
How to remove ads

### ISSUE THREAD

**Issue by visense** [abbasnaqdi/nekoray-macos#45]
How to remove ads  or modify to myself link

<img width="508" alt="iShot_2023-11-04_17 43 16" src="https://github.com/abbasnaqdi/nekoray-macos/assets/3490833/f89a32bf-0be1-41a4-a011-a6fb62c25212">

**Comment by abbasnaqdi** [comment]
Your question is outside the scope of this repository and I don't have an answer for it.
