### ISSUE TITLE
reference is not a tree: e396733db4de15266f0cfdb43c392aca0759324a

### ISSUE THREAD

**Issue by yuranich** [abbasnaqdi/nekoray-macos#49]
keep getting an error on build
`fatal: reference is not a tree: e396733db4de15266f0cfdb43c392aca0759324a`

though I just clone `main` branch and run `bash builder.sh`
on MacOS Venture 13.5.1 intel core.
With `sudo` same error.

Any advice?

**Comment by geneyuriy** [comment]
> keep getting an error on build `fatal: reference is not a tree: e396733db4de15266f0cfdb43c392aca0759324a`
> 
> though I just clone `main` branch and run `bash builder.sh` on MacOS Venture 13.5.1 intel core. With `sudo` same error.
> 
> Any advice?

same issue.

**Comment by abbasnaqdi** [comment]
Fixed
https://github.com/abbasnaqdi/nekoray-macos/releases/tag/3.25
