### ISSUE TITLE
Issue with Hidden Bar

### ISSUE THREAD

**Issue by superkeyor** [abbasnaqdi/nekoray-macos#52]
Hi,

Thanks for your contribution to the community! I have an issue with Hidden Bar on Mac.

I use Hidden Bar (https://apps.apple.com/us/app/hidden-bar/id1452453066?mt=12) to hide certain tray icons. 

Whenever Nekoray-macos GUI restarts, it keeps hidden from Hidden Bar, even though I unhide it earlier. 

Not sure if this Mac specific issue, or an issue related to the upstream nekoray itself.

Do you have any insights?

Thanks!

**Comment by abbasnaqdi** [comment]
Hi, please report this issues to https://github.com/MatsuriDayo/nekoray
