### ISSUE TITLE
Command+Q shows share code instead of quitting

### ISSUE THREAD

**Issue by rjukankukan** [abbasnaqdi/nekoray-macos#61]
Steps to reproduce:
1. Open Nekobox
2. Click Command+Q
3. Observe

Video demo:
https://github.com/abbasnaqdi/nekoray-macos/assets/140888008/5b2ff70a-c3cf-41cd-90cf-9d0db7444146

Also, it would be better if the app will prefer macOS default shortcuts over Windows default shortcuts (f.e. command+backspace instead of del key to delete config etc.)

**Comment by abbasnaqdi** [comment]
This repository only builds the original source for macOS.
To update or fix problems, refer to the main repository.
