### ISSUE TITLE
any way to hide dock icon?

### ISSUE THREAD

**Issue by metya** [abbasnaqdi/nekoray-macos#64]
Hi!
Thanks for your work.
But I was wondering is there any way to hide the dock icon from the dock?

**Comment by Aocro** [comment]
Just add two lines in `nekoray.app\Contents\Info.plist`
```
<key>LSUIElement</key>
<true/>
```

https://discussions.apple.com/thread/7444141?sortBy=best

**Comment by metya** [comment]
Thanks! I know that there is the option to do it by hand edit Plist, but it's more convenient, then it is in the app.
But thank you anyway :)
